site_name: COMP423 Course Notes
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
theme:
  features:
    - content.code.copy
  name: material
  icon: 
    annotation: material/plus-circle
    admonition:
      <type>: material/alert-circle